# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2022-12-29 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('added_at',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-added_at',)},
        ),
    ]
